language: java
jdk:
- oraclejdk8
sudo: required

script: gradle check
branches:
only: master

notifications:
  email: true
  recipients:
   - carlos.gonzales@jalasoft.com
   - AT01@fundacion-jala.org
